export const BASE_CURRENCY_UPDATE = 'session.BASE_CURRENCY_UPDATE';
export const UPDATE_PAGE_TITLE = 'session.UPDATE_PAGE_TITLE';
export const UPDATE_HEADER_LINK = 'session.UPDATE_HEADER_LINK';

export const CURRENCIES_LIST_FETCHED = 'currencies.CURRENCIES_LIST_FETCHED';
